name: MkDocs Deploy (dev)

on:
  workflow_dispatch:
    inputs:
      name:
        description: "MkDocs Deploy"
  push:
    branches:
      - "main"
    paths:
      - "pyblox/**"
      - "docs/**"
      - ".github/workflows/dev-docs.yml"
      - "mkdocs.yml"

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0"
      
      - name: Install dependencies
        run: |
          pip install git+https://github.com/squidfunk/mkdocs-material.git@8.0.0b2
          pip install mkdocstrings httpx mkdocs-literate-nav mkdocs-gen-files mike mkdocs mkdocs-material

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy docs
        run: |
          mike deploy --push dev

                      
      - name: pypi-publish          
        uses: pypa/gh-action-pypi-publish@v1.8.10


