name: MkDocs Deploy (dev)

on:
  workflow_dispatch:
    inputs:
      name:
        description: "MkDocs Deploy"
  push:
    branches:
      - "main"
    paths:
      - "pyblox/**"
      - "docs/**"
      - ".github/workflows/dev-docs.yml"
      - "mkdocs.yml"
permissions: write-all

jobs:
  mkdocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12.0"
      
      - name: Install dependencies
        run: |
          pip install mkdocstrings httpx mkdocs-literate-nav mkdocs-gen-files mike mkdocs mkdocs-material mkdocstrings[python]>=0.18

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      
      - name: Deploy docs
        run: |
          mike deploy --push dev

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Pyblox  # Make sure this path matches your MkDocs build output

          
      - name: pypi-publish          
        uses: pypa/gh-action-pypi-publish@v1.8.10

      - name: Build MkDocs
        run: mkdocs build

      - name: Deploy to GitHub Pages
        run: |
          mkdocs gh-deploy --force
        env:
          MKDOCS_BUILD: true
